In [2]:
import numpy as np

## Vectorized Operations

In [3]:
x = np.array([1,2,3,4])
x+1

array([2, 3, 4, 5])

In [4]:
y=np.array([-1, 2, 3, 0])
x * y

array([-1,  4,  9,  0])

In [5]:
np.dot(x,y)

12

In [6]:
x == y

array([False,  True,  True, False])

In [8]:
x = np.arange(10000)

In [9]:
%timeit x + 1

5.53 µs ± 138 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
y = np.arange(10000)

In [13]:
%timeit [i + 1 for i in y]

2.57 ms ± 21.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Universal functions

In [14]:
x = np.arange(5, 10)
np.square(x)

array([25, 36, 49, 64, 81])

In [15]:
y = np.ones(5) * 10
np.mod(y,x)

array([0., 4., 3., 2., 1.])

In [16]:
np.minimum(x, 7)

array([5, 6, 7, 7, 7])

In [17]:
np.min(x)

5

In [19]:
z = np.repeat(x, 3).reshape(5, 3)
z

array([[5, 5, 5],
       [6, 6, 6],
       [7, 7, 7],
       [8, 8, 8],
       [9, 9, 9]])

In [20]:
np.median(z)

7.0

In [21]:
np.median(z, axis = 0)

array([7., 7., 7.])

In [22]:
np.median(z, axis = 1)

array([5., 6., 7., 8., 9.])

In [23]:
np.add.accumulate(x)

array([ 5, 11, 18, 26, 35])

In [24]:
np.multiply.outer(x,x)

array([[25, 30, 35, 40, 45],
       [30, 36, 42, 48, 54],
       [35, 42, 49, 56, 63],
       [40, 48, 56, 64, 72],
       [45, 54, 63, 72, 81]])