In [1]:
import numpy as np
x = np.array([[1,2,3],[2,3,4]])
print(x)

[[1 2 3]
 [2 3 4]]


In [3]:
print(f"x dimensions {x.ndim}")
print(f"x shape {x.shape}")

x dimensions 2
x shape (2, 3)


In [4]:
x

array([[1, 2, 3],
       [2, 3, 4]])

In [5]:
x.flatten()

array([1, 2, 3, 2, 3, 4])

In [6]:
x = np.random.random((100, 100))

In [7]:
y = x[42, 87]

In [9]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [10]:
c_array = np.random.rand(10000, 10000)
f_array = np.asfortranarray(c_array)

In [11]:
def sum_row(x):
    return np.sum(x[0, :])
def sum_col(x):
    return np.sum(x[:, 0])

In [12]:
%timeit sum_row(c_array)

10.9 µs ± 91.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%timeit sum_row(f_array)

171 µs ± 1.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
%timeit sum_col(c_array)

171 µs ± 2.25 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [15]:
%timeit sum_col(f_array)

11.1 µs ± 234 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
# Generally slicing creates a view and indexing creates a copy
x = np.random.rand(100,10)
y = x[:5, :]
np.may_share_memory(x, y)

True

In [19]:
y = np.empty([5, 10])
y[:] = x[:5, :]
np.may_share_memory(x,y)

False

## Creating arrays

### array function 

In [21]:
x = np.array([1, 2, 3])
y = np.array(['hellow', 'world'])

In [25]:
x = range(5)
y = np.array(x)
z = np.arange(5)
print(y)
print(z)

[0 1 2 3 4]
[0 1 2 3 4]


### random arrays

In [27]:
x = np.random.rand(2,2,2)
print(x.shape)

shape_tuple = (2, 3, 4)
y = np.random.random(shape_tuple)
print(y.shape)

(2, 2, 2)
(2, 3, 4)


In [28]:
LOW, HIGH = 1, 11
SIZE = 10
x = np.random.randint(LOW, HIGH, size=SIZE)
print(x)

[1 2 1 3 9 2 9 6 2 2]


## Array Datatypes

In [30]:
print(x.dtype)
print(y.dtype)

int64
float64


In [35]:
x = np.ones((10, 10), dtype=int)
print(x.dtype)
y = np.zeros((10, 10), dtype='|S1')
print(y.dtype)

int64
|S1
