In [1]:
import numpy as np

## Vectorized Operations

In [3]:
x = np.array([1,2,3,4])
x+1

array([2, 3, 4, 5])

In [4]:
y=np.array([-1, 2, 3, 0])
x * y

array([-1,  4,  9,  0])

In [5]:
np.dot(x,y)

12

In [6]:
x == y

array([False,  True,  True, False])

In [8]:
x = np.arange(10000)

In [9]:
%timeit x + 1

5.53 µs ± 138 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
y = np.arange(10000)

In [13]:
%timeit [i + 1 for i in y]

2.57 ms ± 21.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Universal functions

In [14]:
x = np.arange(5, 10)
np.square(x)

array([25, 36, 49, 64, 81])

In [15]:
y = np.ones(5) * 10
np.mod(y,x)

array([0., 4., 3., 2., 1.])

In [16]:
np.minimum(x, 7)

array([5, 6, 7, 7, 7])

In [17]:
np.min(x)

5

In [19]:
z = np.repeat(x, 3).reshape(5, 3)
z

array([[5, 5, 5],
       [6, 6, 6],
       [7, 7, 7],
       [8, 8, 8],
       [9, 9, 9]])

In [20]:
np.median(z)

7.0

In [21]:
np.median(z, axis = 0)

array([7., 7., 7.])

In [22]:
np.median(z, axis = 1)

array([5., 6., 7., 8., 9.])

In [23]:
np.add.accumulate(x)

array([ 5, 11, 18, 26, 35])

In [24]:
np.multiply.outer(x,x)

array([[25, 30, 35, 40, 45],
       [30, 36, 42, 48, 54],
       [35, 42, 49, 56, 63],
       [40, 48, 56, 64, 72],
       [45, 54, 63, 72, 81]])

## Broadcasting and shape manipulation
Generally there are 2 conditions that have to be met:
 - Two arrays should be of equal dimensions
 - One of them is 1

In [2]:
x = np.array([[0, 0, 0], 
              [10, 10, 10],
              [20, 20, 20]])
y = np.array([1, 2, 3])
x+y

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [4]:
x = np.array([[0], [10], [20]])
x

array([[ 0],
       [10],
       [20]])

In [5]:
x + y

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

### Reshaping NumPy Arrays

In [9]:
x = np.arange(24)
print(x)
x.shape = 2, 3, -1 # -1 means "the remaining shape size, so 4 here"
x

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
x = np.arange(1000000)
x.shape = 100, 100, 100

In [13]:
%timeit x.flatten()

652 µs ± 26.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
%timeit x.ravel()

181 ns ± 1.94 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


### Vector stacking

In [15]:
x = np.arange(0, 10, 2)
y = np.arange(0, -5, -1)
np.vstack([x, y])

array([[ 0,  2,  4,  6,  8],
       [ 0, -1, -2, -3, -4]])

In [16]:
np.hstack([x, y])

array([ 0,  2,  4,  6,  8,  0, -1, -2, -3, -4])

In [17]:
np.dstack([x, y])

array([[[ 0,  0],
        [ 2, -1],
        [ 4, -2],
        [ 6, -3],
        [ 8, -4]]])

In [25]:
x = np.arange(3)
np.resize(x, (8, ))

array([0, 1, 2, 0, 1, 2, 0, 1])

## A boolean mask

In [30]:
x = np.array([1,3,-1,5,7,-1])
mask = (x < 0)
mask

array([False, False,  True, False, False,  True])

In [31]:
mask.sum()

2

In [34]:
x = np.random.random(50)
(x > .5).sum()

20