In [1]:
import numpy as np

## Introducing Strides

In [2]:
x = np.arange(8, dtype = np.int8)
x

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int8)

In [3]:
x.strides

(1,)

In [7]:
str(x.data)

'<memory at 0x7fc38a9c4880>'

In [8]:
x.shape = 2,4
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]], dtype=int8)

In [9]:
x.strides

(4, 1)

In [11]:
x.shape = 1,4,2
x.strides

(8, 2, 1)

In [13]:
x = np.ones((10000,))
y = np.ones((10000 * 100,))[::100]
x.shape, y.shape

((10000,), (10000,))

In [14]:
x == y

array([ True,  True,  True, ...,  True,  True,  True])

In [15]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [16]:
y.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [17]:
x.strides, y.strides

((8,), (800,))

In [18]:
%timeit x.sum()

6.37 µs ± 66.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
%timeit y.sum()

24.8 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Structured arrays

In [20]:
x = np.empty((2,), dtype = ('i4,f4,a10'))
x[:] = [(1,0.5, 'NumPy'), (10,-0.5, 'Essential')]
x

array([( 1,  0.5, b'NumPy'), (10, -0.5, b'Essential')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [21]:
x[0]

(1, 0.5, b'NumPy')

In [22]:
x['f2']

array([b'NumPy', b'Essential'], dtype='|S10')

In [23]:
y = x['f0']
y

array([ 1, 10], dtype=int32)

In [24]:
y[:] = y * 10
y

array([ 10, 100], dtype=int32)

In [25]:
y[:] = y + 0.5
y

array([ 10, 100], dtype=int32)

In [26]:
x

array([( 10,  0.5, b'NumPy'), (100, -0.5, b'Essential')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [27]:
z = np.ones((2,), dtype=('3i4, (2,3)f4'))
z

array([([1, 1, 1], [[1., 1., 1.], [1., 1., 1.]]),
       ([1, 1, 1], [[1., 1., 1.], [1., 1., 1.]])],
      dtype=[('f0', '<i4', (3,)), ('f1', '<f4', (2, 3))])

In [28]:
x.dtype.names

('f0', 'f1', 'f2')

In [29]:
x.dtype.names = ('id', 'value', 'note')
x

array([( 10,  0.5, b'NumPy'), (100, -0.5, b'Essential')],
      dtype=[('id', '<i4'), ('value', '<f4'), ('note', 'S10')])

In [31]:
list_ex = np.zeros((2,), dtype = [('id', 'i4'), ('value', 'f4', (2,))])
list_ex

array([(0, [0., 0.]), (0, [0., 0.])],
      dtype=[('id', '<i4'), ('value', '<f4', (2,))])

In [32]:
dict_ex = np.zeros((2,), dtype = {'names':['id', 'value'], 'formats': ['i4', '2f4']})
dict_ex

array([(0, [0., 0.]), (0, [0., 0.])],
      dtype=[('id', '<i4'), ('value', '<f4', (2,))])

In [33]:
x[['id', 'note']]

array([( 10, b'NumPy'), (100, b'Essential')],
      dtype={'names':['id','note'], 'formats':['<i4','S10'], 'offsets':[0,8], 'itemsize':18})

### Dates and time in NumPy